# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    outputs:
      matrix: ${{ steps.get_file_changes_echo.outputs.matrix }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Get file changes
      id: get_file_changes
      uses: trilom/file-changes-action@v1.2.3
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Echo file changes
      id: get_file_changes_echo
      run: |
        echo ${{ steps.get_file_changes.outputs.files }}

  # This workflow contains a single job called "build"
  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build1
    strategy:
      matrix: ${{ needs.job1.outputs.matrix }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Echo file changes
      id: get_file_changes_echo
      run: |
        echo ${{ needs.job1.outputs.matrix }}
  