# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run a one-line script
      env: 
        TEST: KOKOKOKO
      run: echo Hello, world! $TEST

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
